# Generated by Django 3.2.23 on 2024-01-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
