# Generated by Django 3.2.23 on 2024-01-17 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_company_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(choices=[('alim', 'Alım Teklifi'), ('satis', 'Satış Teklifi')], max_length=10)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.company')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='DESCRIPTION')),
                ('quality', models.CharField(max_length=50, verbose_name='QUALITY')),
                ('size', models.CharField(max_length=20, verbose_name='SIZE (mm)')),
                ('color', models.CharField(max_length=20, verbose_name='COLOR (Ral)')),
                ('paint', models.CharField(max_length=10, verbose_name='PAINT(μm)')),
                ('zinc', models.CharField(max_length=10, verbose_name='ZINC(g/sm)')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='UNIT PRICE (usd/ton)')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity (ton)')),
            ],
        ),
        migrations.CreateModel(
            name='OfferProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.offer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.product')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='products',
            field=models.ManyToManyField(through='pages.OfferProduct', to='pages.Product'),
        ),
    ]
