# Generated by Django 3.2.13 on 2024-01-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_offer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerproduct',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
