# Generated by Django 3.2.13 on 2024-02-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_offerproduct_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='web_site',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
