# Generated by Django 3.2.13 on 2024-02-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_company_web_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='base_customer',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='sub_company',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
